### ISSUE TITLE
Management API v2

### ISSUE THREAD

**Issue by xantari** [Kentico/kontent-management-sdk-net#50]
**Edited by: @petrsvihlik**
Hi, Kentico Kontent community!
We want to rewrite this SDK to support the [Management API v2 endpoints](https://docs.kontent.ai/reference/management-api-v2) and **we need your help**!

We'd really appreciate it if you'd take part in making Kontent's .NET ecosystem amazing and fixed just a single method. @xantari already laid the [foundations of the new API](https://github.com/Kentico/kontent-management-sdk-net/blob/master/Kentico.Kontent.Management/ManagementEndpointUrlBuilderV2.cs) so you can build on his work. Be like @xantari !

We believe that if we distribute the load among all of us, we can get to the finish line sooner!

Current Management API v2 Coverage (what's done and what needs to be done):
- Content Items
  - [x] POST `/{project_id}/items`
  - [x] GET `/{project_id}/items`
  - [x] GET `/{project_id}/items/{item_identifier}`
  - [x] PUT `/{project_id}/items/{item_identifier}`
  - [x] DEL `/{project_id}/items/{item_identifier}`
- Language variants
  - [x] GET `/{project_id}/items/{item_identifier}/variants`
  - [x] GET `/{project_id}/types/{type_identifier}/variants`
  - [x] GET `/{project_id}/types/{type_identifier}/components`
  - [x] GET `/{project_id}/items/{item_identifier}/variants/{language_identifier}`
  - [x] PUT `/{project_id}/items/{item_identifier}/variants/{language_identifier}`
  - [x] DEL `/{project_id}/items/{item_identifier}/variants/{language_identifier}`
- Languages
  - [x] POST `/{project_id}/languages`
  - [x] GET `/{project_id}/languages`
  - [x] GET `/{project_id}/languages/{language_identifier}`
  - [x] PATCH `/{project_id}/languages/{language_identifier}`
- Workflows
  - [x] GET `/{project_id}/workflow`
  - [x] PUT `/{project_id}/items/{item_identifier}/variants/{language_identifier}/workflow/{workflow_step_identifier}`
  - [x] PUT `/{project_id}/items/{item_identifier}/variants/{language_identifier}/publish`
  - [x] PUT `/{project_id}/items/{item_identifier}/variants/{language_identifier}/new-version`
  - [x] PUT `/{project_id}/items/{item_identifier}/variants/{language_identifier}/unpublish-and-archive`
  - [x] PUT `/{project_id}/items/{item_identifier}/variants/{language_identifier}/cancel-scheduled-publish`
  - [x] PUT `/{project_id}/items/{item_identifier}/variants/{language_identifier}/cancel-scheduled-unpublish`
- Content Types
  - [x] POST `/{project_id}/types`
  - [x] GET `/{project_id}/types`
  - [x] GET `/{project_id}/types/{type_identifier}`
  - [x] PATCH `/{project_id}/types/{type_identifier}`
  - [x] DEL `/{project_id}/types/{type_identifier}`
- Content type snippets
  - [x] POST `/{project_id}/snippets`
  - [x] GET `/{project_id}/snippets`
  - [x] GET `/{project_id}/snippets/{snippet_identifier}`
  - [x] PATCH `/{project_id}/snippets/{snippet_identifier}`
  - [x] DEL `/{project_id}/snippets/{snippet_identifier}`
- Taxonomy groups
  - [x] POST `/{project_id}/taxonomies`
  - [x] GET `/{project_id}/taxonomies`
  - [x] GET `/{project_id}/taxonomies/{taxonomy_group_identifier}`
  - [x] PATCH `/{project_id}/taxonomies/{taxonomy_group_identifier}`
  - [x] DEL `/{project_id}/taxonomies/{taxonomy_group_identifier}`
- Assets
  - [x] POST `/{project_id}/files/{file_name}`
  - [x] POST `/{project_id}/assets` (@xantari #59)
  - [x] GET `/{project_id}/assets` (@xantari #59)
  - [x] GET `/{project_id}/assets/{asset_identifier}` (@xantari #59)
  - [x] PUT `/{project_id}/assets/{asset_identifier}` (@xantari #59)
  - [x] DEL `/{project_id}/assets/{asset_identifier}`
  - [x] GET `/{project_id}/folders` (@xantari #59)
  - [x] POST `/{project_id}/folders`
  - [x] PATCH `/{project_id}/folders`
- Projects
  - [x] GET `/{project_id}`
- Project validation
  - [x] POST `/{project_id}/validate`
- Webhooks
  - [x] POST `/{project_id}/webhooks`
  - [x] GET `/{project_id}/webhooks`
  - [x] GET `/{project_id}/webhooks/{webhook_identifier}`
  - [x] DEL `/{project_id}/webhooks/{webhook_identifier}`
  - [x] PUT `/{project_id}/webhooks/{webhook_identifier}/enable`
  - [x] PUT `/{project_id}/webhooks/{webhook_identifier}/disable`
  - Collections
  - [x] GET `/{project_id}/collections`
  - [x] PATCH `/{project_id}/collections`

 💡 If not specified otherwise, endpoints are only part of alpha release #67 

## Additional context
- Don't forget to update the [code generator](https://github.com/Kentico/kontent-generators-net#how-to-use-for-management-sdk) accordingly.

## More resources
- [Latest MAPI Swagger OASv3](https://kcdmaster.blob.core.windows.net/api-reference-specifications/management_api_v2.json) (can be visualized e.g. through https://editor.swagger.io/)
- docs: https://docs.kontent.ai/reference/management-api-v2

**Comment by petrsvihlik** [comment]
Hi @xantari , the .NET SDK for Management API v2 is still under consideration.
In the meantime, you can use the [JavaScript SDK](https://github.com/Kentico/kontent-management-sdk-js) which should have 100% coverage of the API.

**Comment by xantari** [comment]
Any update on this one? We are trying to add "folder path" from a Kentico Asset item to our azure search index, this is all handled via a C# .NET backend API. We need this folder path so that we can filter out certain asset areas (such as excluding all content from /Documents/News Feed Docs". However the V1 management API does not give us any mechanism to interrogate the blob asset to figure out where it is located.

**Comment by petrsvihlik** [comment]
Unfortunately, it still didn't get high enough in our priorities. I'd personally love to have it but it's quite a large project.
We're waiting for more feedback.

**Community: If you're reading this and it's relevant to you, please let us know. A comment or a simple upvote will do!**

**Comment by xantari** [comment]
https://github.com/xantari/kontent-management-sdk-net-v2 I forked this repo, and added a few methods I needed.

The commit that added the features: https://github.com/Kentico/kontent-management-sdk-net/commit/3b5aaf6de8496caea364f95f3eb977b570829643

Basically the library I forked is now a hybrid library. Some functions have switched to V2:

1. ListAssets
2. AssetUpdate
3. AssetUpsert

Added V2 Only feature added:

1. ListFolders

The rest are still V1.

Maybe you could do this approach with the management library so that you can incrementally make improvements to it like this?

The key is having it's own endpoint builder:  https://github.com/Kentico/kontent-management-sdk-net/commit/3b5aaf6de8496caea364f95f3eb977b570829643#diff-0eeea9de523482e247db78c5c9ff7abae70a349920ba0dbd45dd6abe50536b1c

Which uses the EndpointV2 Url instead of EndPoint in ManagementOptions.cs: https://github.com/Kentico/kontent-management-sdk-net/commit/3b5aaf6de8496caea364f95f3eb977b570829643#diff-e9628f541ec74950afecb3ce4843d42ca2f9e3b1e53125fd69c961fa377093eb

I also added a few extension methods to make a parent linking model so you can "traverse the tree": https://github.com/Kentico/kontent-management-sdk-net/commit/3b5aaf6de8496caea364f95f3eb977b570829643#diff-5d106c3c58258741b59dd958adde34c24870bfde1ab2c6c62e488d261cc236cf

Probably easier ways to do some of this, but I threw this together this morning and it appears to give us what we need from our production environment.

**Comment by xantari** [comment]
Updated the comments above. This basically brings the asset functionality mostly up to date with the V2 assets functionality. The things that are missing is the add/update folder functions (which we don't need at the moment) so I didn't add them.

**Comment by xantari** [comment]
If you want I could re-play these updates (without the huge .v2 namespace change) in another forked copy and do a PR... (I don't have ability to complete the unit tests the way you were doing them though, seems to rely on some sort of internal kentico project id for prescribed response models and would require a regeneration of all those responses with the additional attributes I added to the AssetModel

**Comment by petrsvihlik** [comment]
thank you! I will check it out on Friday (hopefully) and let you know

**Comment by petrsvihlik** [comment]
I went through the code and don't have any objections to your approach. I also appreciate the extension methods. This is something we'd like to improve in the future - have a layer of common extensions wrapping multiple API calls into a simple developer-friendly interface.

I like the iterative approach you suggested. This way, we can start bringing in and officializing new functionality created by the community piece by piece until we have full coverage. One of the milestones would be getting rid of the old endpoint builder :)

So if I may ask you - please replay the updates and submit a PR.

In the meantime, I'll recover the API keys necessary for regenerating the test fixtures. The method of regeneration is described here:
https://github.com/Kentico/kontent-management-sdk-net/blob/2c1ca9bde672f65aeed539363e4051ba177c4e4c/Kentico.Kontent.Management.Tests/ManagementClientTests.cs#L32

Your help is highly appreciated and I'll make sure it'll get the deserved visibility! :)

**Comment by petrsvihlik** [comment]
- [Latest MAPI Swagger OASv3](https://kcdmaster.blob.core.windows.net/api-reference-specifications/management_api_v2.json)

API Coverage:
- Content Items
  - [ ] POST `/{project_id}/items`
  - [ ] GET `/{project_id}/items`
  - [ ] GET `/{project_id}/items/{item_identifier}`
  - [ ] PUT `/{project_id}/items/{item_identifier}`
  - [ ] DEL `/{project_id}/items/{item_identifier}`
- Language variants
  - [ ] GET `/{project_id}/items/{item_identifier}/variants`
  - [ ] GET `/{project_id}/types/{type_identifier}/variants`
  - [ ] GET `/{project_id}/types/{type_identifier}/components`
  - [ ] GET `/{project_id}/items/{item_identifier}/variants/{language_identifier}`
  - [ ] PUT `/{project_id}/items/{item_identifier}/variants/{language_identifier}`
  - [ ] DEL `/{project_id}/items/{item_identifier}/variants/{language_identifier}`
- Languages
  - [ ] POST `/{project_id}/languages`
  - [ ] GET `/{project_id}/languages`
  - [ ] GET `/{project_id}/languages/{language_identifier}`
  - [ ] PATCH `/{project_id}/languages/{language_identifier}`
- Workflows
  - [ ] GET `/{project_id}/workflow`
  - [ ] PUT `/{project_id}/items/{item_identifier}/variants/{language_identifier}/workflow/{workflow_step_identifier}`
  - [ ] PUT `/{project_id}/items/{item_identifier}/variants/{language_identifier}/publish`
  - [ ] PUT `/{project_id}/items/{item_identifier}/variants/{language_identifier}/new-version`
  - [ ] PUT `/{project_id}/items/{item_identifier}/variants/{language_identifier}/unpublish-and-archive`
  - [ ] PUT `/{project_id}/items/{item_identifier}/variants/{language_identifier}/cancel-scheduled-publish`
  - [ ] PUT `/{project_id}/items/{item_identifier}/variants/{language_identifier}/cancel-scheduled-unpublish`
- Content Types
  - [ ] POST `/{project_id}/types`
  - [ ] GET `/{project_id}/types`
  - [ ] GET `/{project_id}/types/{type_identifier}`
  - [ ] PATCH `/{project_id}/types/{type_identifier}`
  - [ ] DEL `/{project_id}/types/{type_identifier}`
- Content type snippets
  - [ ] POST `/{project_id}/snippets`
  - [ ] GET `/{project_id}/snippets`
  - [ ] GET `/{project_id}/snippets/{snippet_identifier}`
  - [ ] PATCH `/{project_id}/snippets/{snippet_identifier}`
  - [ ] DEL `/{project_id}/snippets/{snippet_identifier}`
- Taxonomy groups
  - [ ] POST `/{project_id}/taxonomies`
  - [ ] GET `/{project_id}/taxonomies`
  - [ ] GET `/{project_id}/taxonomies/{taxonomy_group_identifier}`
  - [ ] PATCH `/{project_id}/taxonomies/{taxonomy_group_identifier}`
  - [ ] DEL `/{project_id}/taxonomies/{taxonomy_group_identifier}`
- Assets
  - [ ] POST `/{project_id}/files/{file_name}`
  - [ ] POST `/{project_id}/assets`
  - [ ] GET `/{project_id}/assets`
  - [ ] GET `/{project_id}/assets/{asset_identifier}`
  - [ ] PUT `/{project_id}/assets/{asset_identifier}`
  - [ ] DEL `/{project_id}/assets/{asset_identifier}`
  - [ ] GET `/{project_id}/folders`
  - [ ] POST `/{project_id}/folders`
  - [ ] PATCH `/{project_id}/folders`
- Projects
  - [ ] GET `/{project_id}`
- Project validation
  - [ ] POST `/{project_id}/validate`
- Webhooks
  - [ ] POST `/{project_id}/webhooks`
  - [ ] GET `/{project_id}/webhooks`
  - [ ] GET `/{project_id}/webhooks/{webhook_identifier}`
  - [ ] DEL `/{project_id}/webhooks/{webhook_identifier}`

**Comment by Simply007** [comment]
All endpoints should be covered in the new released v3 betas.

Progress of the final release could be tracked here: https://github.com/Kentico/kontent-management-sdk-net/milestone/5
